spring:
  application:
    name: fintech-aggregator
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

providers:
  coingecko:
    base-url: https://api.coingecko.com/api/v3
    fallback-enabled: true
  alphavantage:
    base-url: https://www.alphavantage.co/query
    api-key: TITB8R16MPI2HZBM   # <-- paste your key here
    fallback-enabled: true
  mock:
    mode: BAD_DATA   # Options: FAIL, SLOW, BAD_DATA, RANDOM

logging:
  level:
    com.aggregator.fintech: DEBUG